on: [repository_dispatch]
name: Dispatch
jobs:
  createbranch:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'asdf' }}
    steps:
    - run: |
        git branch -a
        git config --global user.name cueckoo
        git config --global user.email cueckoo@gmail.com
        git checkout -b blah
        echo "Hello" >> README.md
        git add -A
        git commit -am 'A commit'
        git push
