on: [repository_dispatch]
env:
  MYITCV_GITHUB_PAT: ${{ secrets.MYITCV_GITHUB_PAT }}
name: Dispatch
jobs:
  createbranch:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'asdf' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: git branch -a
    - run: git config --global user.name cueckoo
    - run: git config --global user.email cueckoo@gmail.com
    - run: git config -l
    - run: |-
        git config http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n myitcv:$MYITCV_GITHUB_PAT | base64)"
    - run: git config -l
    - run: git checkout -b blah
    - run: echo "Hello" >> README.md
    - run: git add -A
    - run: git commit -am 'A commit'
    - run: git push origin blah
