on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Git config
      run: git config --global user.name myitcv && git config --global user.email paul@myitcv.io
    - run: echo "https://myitcv:${{ secrets.myitcv_github_pat }}@github.com" > ~/.git-credentials
    - run: cat ~/.git-credentials
    - name: Push
      run: git push origin testing:asdf
