on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Git config
      run: git config --global user.name myitcv && git config --global user.email blah@blah.com
    - name: Make change
      run: echo Hello >> README.md
    - run: git branch -a
    - run: git remote -v
    - name: Commit
      run: git add -A && git commit -am 'A change'
    - name: Push
      run: git push origin
